### ISSUE TITLE
Narrow border

### ISSUE THREAD

**Issue by mfikes** [replete-repl/replete-web#51]
The whitespace here feels a little too narrow:

<img width="697" alt="Napkin 07-06-19, 8 35 01 AM" src="https://user-images.githubusercontent.com/1723464/60756214-f25d7f00-9fc8-11e9-82f0-90adc2a2bf15.png">

I guess that could be fixed by moving that thin line to be closer to the edge (rather than by simply adding more white space).

**Comment by raymcdermott** [comment]
<img width="321" alt="image" src="https://user-images.githubusercontent.com/120437/62078517-1705e900-b24d-11e9-926e-691bb233cab9.png">

How about this? The line is now closer to the edge. I can easily add more padding to the box but I'm not exactly sure what the problem is.

**Comment by mfikes** [comment]
<img width="585" alt="Napkin 07-29-19, 5 10 32 PM" src="https://user-images.githubusercontent.com/1723464/62082934-c5953400-b223-11e9-93b1-2665cc5eef88.png">

Yeah, I can see the line is now indeed closer to the edge. Something still looks slightly cramped to me. But, maybe it is just me.

**Comment by raymcdermott** [comment]
How would you compare it to the iOS layout?
![Image from iOS](https://user-images.githubusercontent.com/120437/62142506-c2b34580-b2ee-11e9-9b8c-4e6dcab68c0a.png)

**Comment by raymcdermott** [comment]
I could remove the lines completely for example, at least for the upper window

**Comment by mfikes** [comment]
Ahh yeah, removing the lines would even make things look more consistent.

**Comment by raymcdermott** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/120437/62493468-7f1a7900-b7d1-11e9-9d01-164ce956e57e.png">


^^^ Better?

**Comment by mfikes** [comment]
Yeah, I think so :)

**Comment by raymcdermott** [comment]
update deployed https://repl.replete-web.io
