### ISSUE TITLE
Functions can't be defined

### ISSUE THREAD

**Issue by ghost** [replete-repl/replete-web#59]
![Screen Shot 2019-09-17 at 23 46 26](https://user-images.githubusercontent.com/40649551/65112472-6b079100-d9a5-11e9-9f33-c09949fe7fd9.png)

**Comment by raymcdermott** [comment]
After redeploy

<img width="689" alt="image" src="https://user-images.githubusercontent.com/120437/65281961-0a5a8e80-db34-11e9-9239-5656fa67c387.png">
